FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

ENV PATH="$PATH:/root/.dotnet/tools"
RUN dotnet tool install dotnet-roundhouse -g --version 1.3.1

WORKDIR /app
COPY sql ./sql

ENTRYPOINT [ "rh", "--connectionstring=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=lifebalance;Pooling=true", "--connstringadmin=User ID=postgres;Password=Pass1234!;Host=postgresdb;Port=5432;Database=postgres;Pooling=true", "--sqlfilesdirectory=sql", "--databasetype=postgres","--silent","--wt=true" ]