namespace LifeBalance.Application.Exceptions;

public static class ExceptionErrorCode
{
    public const string ERROR_ENTITY_NOT_FOUND = "ERROR.ENTITY.NOT_FOUND";
    public const string ERROR_ENTITY_VALIDATION = "ERROR.ENTITY.VALIDATION";
    public const string ERROR_ENTITY_INVALID = "ERROR.ENTITY.INVALID";
    public const string ERROR_GENERIC_COMMON_EXCEPTION = "ERROR.GENERIC.COMMON_EXCEPTION";

    public static class DetailCode
    {
        public const string ERROR_VALIDATION = "ERROR.VALIDATION.FAILED";
        public const string ERROR_VALIDATION_REQUIRED = "ERROR.ENTITY.VALIDATION.FIELD_REQUIRED";
        public const string ERROR_VALIDATION_SOME_ITEMS_DELETED = "ERROR.ENTITY.VALIDATION.SOME_ITEMS_DELETED";
        public const string ERROR_VALIDATION_DUPLICATED = "ERROR.ENTITY.VALIDATION.FIELD_DUPLICATED";
        public const string ERROR_VALIDATION_NOT_FOUND = "ERROR.ENTITY.VALIDATION.FIELD_NOT_FOUND";
        public const string ERROR_ENTITY_NOT_FOUND_SOME_ITEMS_DELETED = "ERROR.ENTITY.NOT_FOUND.SOME_ITEMS_DELETED";
        public const string ERROR_VALIDATION_NOT_ACTIVE = "ERROR.ENTITY.VALIDATION.FIELD_NOT_ACTIVE";
        public const string ERROR_VALIDATION_INVALID = "ERROR.ENTITY.VALIDATION.FIELD_INVALID";
        public const string ERROR_VALIDATION_MAX_LENGTH = "ERROR.ENTITY.VALIDATION.MAX_LENGTH";
    }
}