//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeBalance.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Workouts_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workouts_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeBalance.Api.Resources.Workouts.en", typeof(Workouts_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build lower-body strength|Develop glutes and quads|Improve core stability|Increase calorie burn.
        /// </summary>
        internal static string Workout_GYM1_Benefits {
            get {
                return ResourceManager.GetString("Workout.GYM1.Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg &amp; Glute Workout.
        /// </summary>
        internal static string Workout_GYM1_Name {
            get {
                return ResourceManager.GetString("Workout.GYM1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tempo 3-1-1 = 3 seconds down – 1 second pause – 1 second up.
        ///RPE 7–9 for hypertrophy (1–3 reps in reserve).
        ///Brace your core as if preparing to be punched to protect your spine.
        ///        .
        /// </summary>
        internal static string Workout_GYM1_Notes {
            get {
                return ResourceManager.GetString("Workout.GYM1.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Target muscles: quadriceps, glutes, core.
        ///
        ///Setup:
        ///- Feet shoulder-width or slightly wider, toes turned out 15–30°
        ///- Weight balanced over mid-foot
        ///- Neutral spine, chest open, eyes forward
        ///
        ///Execution:
        ///- Inhale deeply and brace your core
        ///- Descend by pushing hips back while knees track over toes
        ///- Lower until you can maintain a neutral spine (thighs parallel is a common reference)
        ///- Drive up by pushing the floor away, keeping knees aligned
        ///
        ///Coaching cues:
        ///- “Sit down as if onto a chair”
        ///- “Ri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Workout_GYM1_Step_GYM1_STEP1_Description {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.GYM1_STEP1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squat (Goblet / Back Squat).
        /// </summary>
        internal static string Workout_GYM1_Step_GYM1_STEP1_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.GYM1_STEP1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///3–5 minutes: incline walking or light cycling to raise body temperature.
        ///
        ///2–3 minutes:
        ///- Glute bridge: 2 × 12 reps
        ///- Bodyweight squat: 2 × 10 reps
        ///
        ///Ramp-up sets for the main lift:
        ///- 1 very light set × 10–12 reps
        ///- 1 moderate set × 5–6 reps
        ///        .
        /// </summary>
        internal static string Workout_GYM1_Step_warmup_Description {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.warmup.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Warm-up (7–10 minutes).
        /// </summary>
        internal static string Workout_GYM1_Step_warmup_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.warmup.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Body – Squat Focus.
        /// </summary>
        internal static string Workout_GYM1_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Title", resourceCulture);
            }
        }
    }
}
