//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeBalance.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Workouts_vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workouts_vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeBalance.Api.Resources.Workouts.vi", typeof(Workouts_vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng sức mạnh thân dưới|Phát triển mông và đùi|Cải thiện độ ổn định core|Đốt nhiều calo hơn.
        /// </summary>
        internal static string Workout_GYM1_Benefits {
            get {
                return ResourceManager.GetString("Workout.GYM1.Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài tập Chân &amp; Mông.
        /// </summary>
        internal static string Workout_GYM1_Name {
            get {
                return ResourceManager.GetString("Workout.GYM1.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Tempo 3-1-1 = xuống 3 giây – dừng 1 giây – lên 1 giây.
        ///RPE 7–9 cho tăng cơ (còn dư 1–3 reps).
        ///Brace = gồng bụng như chuẩn bị bị đấm để bảo vệ cột sống.
        ///        .
        /// </summary>
        internal static string Workout_GYM1_Notes {
            get {
                return ResourceManager.GetString("Workout.GYM1.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Nhóm cơ chính: đùi trước, mông, core.
        ///
        ///Setup:
        ///- Chân rộng bằng vai hoặc hơn chút, mũi chân mở 15–30°
        ///- Trọng tâm ở giữa bàn chân
        ///- Lưng trung lập, ngực mở, mắt nhìn thẳng
        ///
        ///Cách thực hiện:
        ///- Hít sâu và brace (gồng bụng)
        ///- Hạ xuống bằng cách đẩy hông ra sau, gối theo hướng mũi chân
        ///- Xuống tới mức vẫn giữ được lưng trung lập (đùi song song sàn là mốc phổ biến)
        ///- Đứng lên bằng cách “đẩy sàn”, giữ gối ổn định
        ///
        ///Cues dễ nhớ:
        ///- “Ngồi xuống như ngồi ghế”
        ///- “Gồng bụng, kẹp sườn”
        ///- “Gối mở nhẹ ra ng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Workout_GYM1_Step_GYM1_STEP1_Description {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.GYM1_STEP1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squat (Goblet / Back Squat).
        /// </summary>
        internal static string Workout_GYM1_Step_GYM1_STEP1_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.GYM1_STEP1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///3–5 phút: đi bộ dốc hoặc đạp xe nhẹ để làm nóng cơ thể.
        ///
        ///2–3 phút:
        ///- Glute bridge: 2 × 12 lần
        ///- Squat không tạ: 2 × 10 lần
        ///
        ///Ramp-up cho bài chính:
        ///- 1 set tạ rất nhẹ × 10–12 reps
        ///- 1 set tạ vừa × 5–6 reps
        ///        .
        /// </summary>
        internal static string Workout_GYM1_Step_warmup_Description {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.warmup.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khởi động chuẩn (7–10 phút).
        /// </summary>
        internal static string Workout_GYM1_Step_warmup_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Step.warmup.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thân Dưới – Trọng Tâm Squat.
        /// </summary>
        internal static string Workout_GYM1_Title {
            get {
                return ResourceManager.GetString("Workout.GYM1.Title", resourceCulture);
            }
        }
    }
}
