CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL,
    email VARCHAR(128) NULL,
    name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_logins (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    provider VARCHAR(64) NOT NULL,
    provider_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_logins PRIMARY KEY (id),
    CONSTRAINT fk_user_logins_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);